DROP TABLE IF EXISTS TBL_EMPLOYEES;

CREATE TABLE CUSTOMER (
  arn INT AUTO_INCREMENT  PRIMARY KEY,
  firstName VARCHAR(250) NOT NULL,
  lastName VARCHAR(250) NOT NULL,
  middleName VARCHAR(250) NOT NULL,
  phoneNumber VARCHAR(250) NOT NULL,
  emailAddress VARCHAR(250) DEFAULT NULL
);